- .github/workflows/docker.yml
Implement pipeline to publish skandha image to DockerHub
> Implement docker build/publish pipeline

- .gitignore
- packages/api/package.json
- packages/api/src/app.ts
- packages/api/src/constants.ts
- packages/api/src/modules/eth.ts
- packages/cli/src/cmds/start/handler.ts
- packages/cli/src/options/bundlerOptions/executor.ts
- packages/db/package.json
- packages/db/src/index.ts
- packages/db/src/localDb.ts
- packages/db/src/rocksDb.ts
- packages/executor/customTracer.js
- packages/executor/package.json
- packages/executor/src/entities/MempoolEntry.ts
- packages/executor/src/executor.ts
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/EventsService.ts
- packages/executor/src/services/MempoolService.ts
- packages/executor/src/services/ReputationService.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/types/src/db/IDbController.ts
- packages/types/src/db/index.ts
- packages/types/src/index.ts
- packages/types/src/networks/networks.ts
- add base network
- fix geth tracer
- remove "db" package from "executor" package and replace all instances of db with interface
- feat: in-memory db controller (similar to rocksdb controller)
- added new rpc method for userOp validation (opcode + gas fee validation)
> add base & fix tracer

- README.md
- packages/cli/src/cmds/start/handler.ts
- packages/cli/src/options/bundlerOptions/executor.ts
- packages/cli/src/options/bundlerOptions/options.ts
- packages/executor/src/config.ts
- packages/executor/src/executor.ts
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/executor/src/services/index.ts
- packages/params/README.md
- packages/params/package.json
- packages/params/src/bannedContracts.ts
- packages/params/src/index.ts
- packages/params/tsconfig.build.json
- packages/types/src/networks/networks.ts
- yarn.lock
- added a new package "params"
- feat: ban non-deterministic precompiled contracts during userOp validation
https://github.com/etherspot/skandha/blob/141f861195e58a151f78b262ac8f1b37e5682634/packages/params/src/bannedContracts.ts#L1-L22
https://github.com/etherspot/skandha/blob/141f861195e58a151f78b262ac8f1b37e5682634/packages/executor/src/services/UserOpValidation.ts#L456-L474
- env vars for entrypoints and supported networks
> ban non-deterministic precompiled contracts

- README.md
- packages/cli/src/cmds/start/handler.ts
- packages/cli/src/cmds/start/index.ts
- packages/executor/src/config.ts
- packages/executor/src/executor.ts
- packages/executor/src/modules/eth.ts
- packages/executor/src/modules/web3.ts
- packages/executor/src/services/BundlingService.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/executor/tsconfig.build.json
Introduced unsafe mode - bypasses opcode & stake check (bypasses `debug_traceCall` basically)
> feat: unsafe mode

- .github/workflows/check-package-version.yml
- .github/workflows/release.yml
- Add pipeline config to create GH release
- Add pipeline config to check if the version is updated in `package.json`
> Implement gh release and version check pipelines

- packages/types/src/networks/networks.ts
previously goerli was removed: https://github.com/etherspot/skandha/pull/16/commits/2d7cb0e8aba491f672e687523ac60eb8cd9d0855
> bringing goerli back temporarily

- lerna.json
- package.json
- packages/api/package.json
- packages/api/src/constants.ts
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/params/package.json
Added support for redirection for `eth_sendRawTransaction`
> Eth method changes

- lerna.json
- package.json
- packages/api/package.json
- packages/api/src/logger.ts
- packages/api/src/modules/redirect.ts
- packages/cli/package.json
- packages/cli/src/cmds/start/handler.ts
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/BundlingService.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/params/package.json
- packages/types/package.json
- packages/types/src/networks/networks.ts
Made all interactions with the rpc providers compatible with Nethermind, though there are still some issues that we can't fix on our side:
1. some versions Nethermind return "0x" in the data field if the error consist of only the error selector (https://github.com/NethermindEth/nethermind/issues/5740)
2. tracing with custom tracers don't work, so the bundler should be ran in the unsafeMode for Nethermind nodes
Onchain tx example: https://gnosisscan.io/tx/0xbf2a14935f4f1e663f560862ffac76d16146632cffddbb5f5b6972dc79fd69e1
Tested the branch against https://github.com/eth-infinitism/bundler-spec-tests/commit/c6dae4c242e25d7b18f4a243d1cea0a7d676a95e with EP v6
> Gnosis chain fixes

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/executor.ts
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/BundlingService.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/executor/src/utils/getGasFee.ts
- packages/params/package.json
- packages/params/src/eip1559.ts
- packages/params/src/index.ts
- packages/types/package.json
Test tx: https://explorer.fuse.io/tx/0xc0a4f95bc7ba20af36c41715bf39aa3a20dad541b0e72ac610de096252eb95c8
> disable eip1559 for fuse

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- README.md
- package.json
- Added https://skandha.run one-liner script
- Added engine requirement for node >=18
- Added PR, bug and feature request template 
-
> Add  one-liner script, engine requirement and issue templates [ci skip]

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/params/package.json
- packages/params/src/gas-estimation/index.ts
- packages/params/src/gas-estimation/optimism.ts
- packages/params/src/index.ts
- packages/types/package.json
- yarn.lock
> add additional pvg for optimism

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/utils/getGasFee.ts
- packages/params/package.json
- packages/types/package.json
> feat: use etherscan for optimism gas fees

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/utils/getGasFee.ts
- packages/params/package.json
- packages/types/package.json
> matic gas oracle fix

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/cli/src/cmds/start/handler.ts
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/config.ts
- packages/executor/src/executor.ts
- packages/executor/src/interfaces.ts
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/params/package.json
- packages/params/src/constants.ts
- packages/params/src/index.ts
- packages/types/package.json
- switch from `simulateValidation` to `simulateHandleOp` - ECDSA signatures can be set to "0x" during estimation
- fix callGasLimit estimation
Tested with ERC20 transfer on a fresh wallet:
Estimated callGasLimit before: `0x5820` = `22560`
Estimated callGasLimit after: `0xda69` = `55913`
Example tx with fixed callGasLimit: https://mumbai.polygonscan.com/tx/0x8fca08aa8fe2575538844ad7fe192c05ed6d7ff8f6725a894c013bd9d10a6e9c
-
> Simulate handle op

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/services/UserOpValidation.ts
- packages/params/package.json
- packages/types/package.json
- there was a typo in the previous release. simulateHandleOp should only be used during estimation, not validation
-
> fix: use simulateValidation during validation

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/params/package.json
- packages/types/package.json
- moving check for execution revert below simulateHandleOps, otherwise we're not getting proper error message in some scenarious
-
> check for execution revert after simulateHandleOps

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/params/package.json
- packages/types/package.json
- calculate callGasLimit based on paid fee only for undeployed wallets
- for deployed wallets use the previous `estimateGas` method, because the paid fee maybe less due to accumulated balance of the wallet from previous userops
-
> fix callGasLimit calculation

- .github/workflows/bundler-spec-tests.yml
- .github/workflows/release.yml
- Added (erc4337 compliance) bundler spec tests pipeline  https://github.com/eth-infinitism/bundler-spec-tests (currently it checkouts to #54) should be changed once PR is merged.
- Added support for arm64 docker image architecture
-
> Add bundler spec tests pipeline and support for arm64 arch docker image

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/config.ts
- packages/executor/src/interfaces.ts
- packages/executor/src/modules/eth.ts
- packages/params/package.json
- packages/types/package.json
> Configurable receipt range

- .github/workflows/release.yml
-  As unable to build image in arm based arch (https://github.com/etherspot/skandha/actions) , revert back old pipeline 
-
> [FIX] Revert back old pipeline config

- lerna.json
- package.json
- packages/api/package.json
- packages/api/src/app.ts
- packages/api/src/constants.ts
- packages/api/src/modules/eth.ts
- packages/api/src/modules/skandha.ts
- packages/api/src/server.ts
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/config.ts
- packages/executor/src/executor.ts
- packages/executor/src/interfaces.ts
- packages/executor/src/modules/index.ts
- packages/executor/src/modules/skandha.ts
- packages/executor/src/services/BundlingService.ts
- packages/executor/src/utils/gas-oracles/arbitrum.ts
- packages/executor/src/utils/gas-oracles/index.ts
- packages/executor/src/utils/gas-oracles/interfaces.ts
- packages/executor/src/utils/gas-oracles/matic.ts
- packages/executor/src/utils/gas-oracles/mumbai.ts
- packages/executor/src/utils/gas-oracles/optimism.ts
- packages/executor/src/utils/gas-oracles/utils.ts
- packages/executor/src/utils/getGasFee.ts
- packages/params/package.json
- packages/types/package.json
- packages/types/src/api/errors/rpc-error-codes.ts
- packages/types/src/api/interfaces.ts
- added `skandha_getGasPrice` rpc method
- fixed env var issue for chains with names like baseGoerli, mantleTestnet, etc.
- added etherscan gas oracle for arbitrum
- silenced logger on `GET /version` 
-
> feat: gas price rpc

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/params/package.json
- packages/types/package.json
- added default values for gas limit during estimation, because callGasLimit = 0 results in wrong estimation
-
> fallback values for gas limits during estimation

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/cli/src/cmds/start/handler.ts
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/services/UserOpValidation.ts
- packages/params/package.json
- packages/params/src/types/IWhitelistedEntities.ts
- packages/params/src/whitelisted-entities/accounts.ts
- packages/params/src/whitelisted-entities/factories.ts
- packages/params/src/whitelisted-entities/index.ts
- packages/params/src/whitelisted-entities/paymasters.ts
- packages/types/package.json
- whitelisted Pimlico's and Stackup's paymasters
- Tested with Stackup's paymaster (Mumbai is down atm, will attach the link to the tx later)
-
> feat: whitelist paymasters

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/params/package.json
- packages/types/package.json
- always set gas limits to max values during estimation
- fix the issue when maxFeePerGas couldn't be set to 0 (#64)
-
> Fix estimate gas

- .github/workflows/lint-pr.yml
- .github/workflows/release-dev.yml
- Added pipeline to lint PR title and release unstable pipeline
-
> feat: lint pr and dev/unstable release pipeline

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/customTracer.js
- packages/executor/package.json
- packages/executor/src/config.ts
- packages/executor/src/executor.ts
- packages/executor/src/interfaces.ts
- packages/executor/src/modules/eth.ts
- packages/executor/src/services/BundlingService.ts
- packages/executor/src/services/GethTracer.ts
- packages/executor/src/services/MempoolService.ts
- packages/executor/src/services/ReputationService.ts
- packages/executor/src/services/UserOpValidation.ts
- packages/executor/src/utils/mergeStorageMap.ts
- packages/params/package.json
- packages/types/package.json
- feat: conditional transactions
- feat: separate configurable rpc endpoint that is used only for submitting bundles
On chain test: https://goerli.arbiscan.io/tx/0x1b5fea9c043211ccc1f21ce211c2d00e86bdfbeeafe391f27831ae41c298c55e
-
> conditional transactions & separate rpc for submission

- packages/executor/src/services/GethTracer.ts
> remove unused import

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/params/package.json
- packages/types/package.json
- If callGasLimit calculated on paid fee is smaller that result returned by `eth_estimateGas`, use the larger one. 
-
> Use Larger Estimated callGasLimit

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/params/package.json
- packages/types/package.json
- packages/types/src/networks/networks.ts
- yarn.lock
- added linea & linea testnet
-
> feat: linea & linea testnet

- .github/workflows/bundler-spec-tests.yml
- .github/workflows/check-package-version.yml
- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/params/package.json
- packages/params/src/eip1559.ts
- packages/types/package.json
- packages/types/src/networks/networks.ts
- Added Scroll mainnet and Scroll Alpha and Sepolia testnets
- Added dry-run build pipeline
- Checkout to specific commit needed for spec tests due to changed EP address
-
> feat: Added Scroll, dry-run build and fixed spec tests

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/services/UserOpValidation/GethTracer.ts
- packages/params/package.json
- packages/types/package.json
- renamed `gasLimit` field to `gas` on debug_traceCall. GasLimit doesn't work properly sometimes
-
> rename gasLimit to gas

- README.md
- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/modules/eth.ts
- packages/executor/src/utils/gas-oracles/interfaces.ts
- packages/executor/src/utils/gas-oracles/mantle.ts
- packages/executor/src/utils/getGasFee.ts
- packages/params/package.json
- packages/types/package.json
- packages/types/src/api/interfaces.ts
- yarn.lock
- Added l1 cost to mantle fees
- Added maxFeePerGas and maxPriorityFeePerGas in `eth_estimateUserOperationGas` endpoint. To properly estimate the L1 cost of a tx, we need to know the content of the tx, so it's best to put those two fields there because they depend on the userop
-
> Gas prices in estimation endpoint & add l1 cost in mantle fees

- lerna.json
- package.json
- packages/api/package.json
- packages/api/src/app.ts
- packages/api/src/modules/redirect.ts
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/params/package.json
- packages/types/package.json
- error parsing worked incorrectly on calls that reverted with `execution reverted` messages and without data
-
> fix error parsing on redirected calls

- lerna.json
- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/executor/src/services/UserOpValidation/validators/safe.ts
- packages/params/package.json
- packages/params/src/whitelisted-entities/factories.ts
- packages/types/package.json
- added etherspot-prime factories to the whitelist
-
> Whitelist etherspot factories

- .github/workflows/release.yml
- Fix by removing arm64 because it fails https://github.com/etherspot/skandha/actions
- This change was reverted from #90 PR
-
> fix: stuck build step

- .github/workflows/bundler-spec-tests.yml
- Fix compliance tests as deployed different EntryPoint address other than v0.6.0
-
> fix: erc4337 compliance tests pipeline

- README.md
Including the video link in the readme.
> Add run Skandha video link to README [skip ci]

- .github/workflows/release-p2p.yml
- Create GH actions pipeline for EP6 P2P 
-
> feat: Create pipeline config for EP6 P2P

- packages/contracts/package.json
- yarn.lock
> fix docker build

- README.md
- config.json.default
- packages/api/package.json
- tsconfig.build.json
- yarn.lock
- updated class-validator package (old version got bugs recently)
- updated readme
-
> version 2: fix deps & update readme

- packages/executor/src/services/BundlingService/service.ts
- packages/node/src/network/peers/discover.ts
- packages/node/src/network/peers/peerManager.ts
- packages/node/src/network/reqresp/ReqRespNode.ts
- packages/node/src/reqresp/request/errors.ts
- packages/node/src/reqresp/request/index.ts
> chore: fix some typos

- .github/workflows/release.yml
- try publishing without building binaries
-
> npm followup

- package.json
- packages/api/package.json
- packages/cli/package.json
- packages/contracts/package.json
- packages/db/package.json
- packages/executor/package.json
- packages/monitoring/package.json
- packages/node/package.json
- packages/params/package.json
- packages/types/package.json
- packages/utils/package.json
> make packages public

- package.json
- `lerna bootstrap` is occassionaly failing after making all packages public - updated lerna and removed `lerna bootstrap` as suggested here https://lerna.js.org/docs/legacy-package-management#migrating-from-lerna-bootstrap-lerna-add-and-lerna-link-in-lerna-v7-and-later
-
> update lerna & remove lerna bootstrap

- CONTRIBUTING.md
- Dockerfile
> remove lerna bootstrap from Dockerfile

- .github/workflows/release-dev.yml
- .github/workflows/release.yml
- README.md
- https://github.com/etherspot/skandha/pull/204
- Added release tags as:  `v1-{version}` and `v2-{version}`  
- Example: v1-1.0.0 and v2-2.0.0
- `latest` tag has been removed
- Added info on readme for both versions
-
> (v1) fix: release tagging

- Dockerfile
> dockerfile: increase network timeout limit

- docs/p2p.md
> doc: add docs on fastlane

- README.md
- Add hosted version feature in readme
-
> chore: add hosted version in readme [skip ci]

- packages/executor/src/modules/skandha.ts
- packages/types/src/api/interfaces.ts
- config response will now return boolean if tenderly is set
-
> fixing config response to omit tenderly api and key

- packages/executor/src/config.ts
- packages/executor/src/interfaces.ts
- packages/executor/src/modules/skandha.ts
- packages/executor/src/services/UserOpValidation/validators/tenderly.ts
- packages/executor/src/services/UserOpValidation/validators/unsafe.ts
- packages/types/src/api/interfaces.ts
- added tenderly save to config
-
> adding tenderly save to config

- packages/executor/src/modules/eth.ts
- packages/executor/src/modules/skandha.ts
- packages/executor/src/services/BundlingService/relayers/base.ts
- packages/executor/src/services/BundlingService/utils/eip7702.ts
- packages/types/src/api/interfaces.ts
- adding eip7702 property to skandha_config
- using viem for estimate call
- changes for replace regex
-
> fix: skandha_config, hex replacementfor 0x0, using viem for estimate call

- .github/workflows/release-ep6.yml
- .github/workflows/release-ep7.yml
- README.md
> chore: Pipeline changes EP7 (v2)
